import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787038967655 implements MigrationInterface {
    name = 'InitialSchema1787038967655'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "fk_bookings_user"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "fk_bookings_room"`);
        await queryRunner.query(`ALTER TABLE "images" DROP CONSTRAINT "fk_images_room"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "fk_room_amenities_room"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "fk_room_amenities_amenity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_room_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_check_in_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_check_out_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_images_room_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "chk_bookings_dates"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "chk_bookings_total_amount"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "chk_rooms_capacity"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "chk_rooms_price"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_pkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(20) NOT NULL DEFAULT 'USER'`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_pkey"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "room_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "room_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "payment_status"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "payment_status" character varying(20) NOT NULL DEFAULT 'UNPAID'`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."booking_status_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "status" character varying(20) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "images" DROP CONSTRAINT "images_pkey"`);
        await queryRunner.query(`ALTER TABLE "images" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "images" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "images" ADD CONSTRAINT "PK_1fe148074c6a1a91b63cb9ee3c9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "images" DROP COLUMN "room_id"`);
        await queryRunner.query(`ALTER TABLE "images" ADD "room_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "images" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "images" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "rooms_pkey"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."room_status_enum"`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "status" character varying(20) NOT NULL DEFAULT 'AVAILABLE'`);
        await queryRunner.query(`ALTER TABLE "rooms" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rooms" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "room_amenities_pkey"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "room_amenities_pkey" PRIMARY KEY ("amenity_id")`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP COLUMN "room_id"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD "room_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "room_amenities_pkey"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "room_amenities_pkey" PRIMARY KEY ("amenity_id", "room_id")`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "room_amenities_pkey"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "PK_1bbdd33b01f2e52f4dd50743544" PRIMARY KEY ("room_id")`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP COLUMN "amenity_id"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD "amenity_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "PK_1bbdd33b01f2e52f4dd50743544"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "PK_6873eccbd044cfef35305a21671" PRIMARY KEY ("room_id", "amenity_id")`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "amenities" DROP CONSTRAINT "amenities_pkey"`);
        await queryRunner.query(`ALTER TABLE "amenities" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "amenities" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "amenities" ADD CONSTRAINT "PK_c0777308847b3556086f2fb233e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "amenities" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "amenities" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_64cd97487c5c42806458ab5520c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_0b0fc32fe6bd0119e281628df7a" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "images" ADD CONSTRAINT "FK_1584086cb823cdf223dbf9ded3e" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "FK_1bbdd33b01f2e52f4dd50743544" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "FK_936612d991e2522e82cd86fa106" FOREIGN KEY ("amenity_id") REFERENCES "amenities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "FK_936612d991e2522e82cd86fa106"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "FK_1bbdd33b01f2e52f4dd50743544"`);
        await queryRunner.query(`ALTER TABLE "images" DROP CONSTRAINT "FK_1584086cb823cdf223dbf9ded3e"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_0b0fc32fe6bd0119e281628df7a"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_64cd97487c5c42806458ab5520c"`);
        await queryRunner.query(`ALTER TABLE "amenities" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "amenities" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "amenities" DROP CONSTRAINT "PK_c0777308847b3556086f2fb233e"`);
        await queryRunner.query(`ALTER TABLE "amenities" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "amenities" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "amenities" ADD CONSTRAINT "amenities_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "PK_6873eccbd044cfef35305a21671"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "PK_1bbdd33b01f2e52f4dd50743544" PRIMARY KEY ("room_id")`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP COLUMN "amenity_id"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD "amenity_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "PK_1bbdd33b01f2e52f4dd50743544"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "room_amenities_pkey" PRIMARY KEY ("amenity_id", "room_id")`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "room_amenities_pkey"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "room_amenities_pkey" PRIMARY KEY ("amenity_id")`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP COLUMN "room_id"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD "room_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "room_amenities_pkey"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "room_amenities_pkey" PRIMARY KEY ("room_id", "amenity_id")`);
        await queryRunner.query(`ALTER TABLE "rooms" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rooms" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."room_status_enum" AS ENUM('AVAILABLE', 'OCCUPIED', 'MAINTENANCE')`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "status" "public"."room_status_enum" NOT NULL DEFAULT 'AVAILABLE'`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "rooms_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "images" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "images" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "images" DROP COLUMN "room_id"`);
        await queryRunner.query(`ALTER TABLE "images" ADD "room_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "images" DROP CONSTRAINT "PK_1fe148074c6a1a91b63cb9ee3c9"`);
        await queryRunner.query(`ALTER TABLE "images" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "images" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "images" ADD CONSTRAINT "images_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."booking_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "status" "public"."booking_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "payment_status"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('UNPAID', 'PAID', 'REFUNDED')`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "payment_status" "public"."payment_status_enum" NOT NULL DEFAULT 'UNPAID'`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "room_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "room_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "user_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "PK_bee6805982cc1e248e94ce94957"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('USER', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."user_role_enum" NOT NULL DEFAULT 'USER'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."user_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "chk_rooms_price" CHECK ((price_per_night >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "chk_rooms_capacity" CHECK ((capacity > 0))`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "chk_bookings_total_amount" CHECK ((total_amount >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "chk_bookings_dates" CHECK ((check_out_date > check_in_date))`);
        await queryRunner.query(`CREATE INDEX "idx_images_room_id" ON "images" USING btree ("room_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_check_out_date" ON "bookings" USING btree ("check_out_date") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_check_in_date" ON "bookings" USING btree ("check_in_date") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_room_id" ON "bookings" USING btree ("room_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_user_id" ON "bookings" USING btree ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_status" ON "bookings" USING btree ("status") `);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "fk_room_amenities_amenity" FOREIGN KEY ("amenity_id") REFERENCES "amenities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "fk_room_amenities_room" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "images" ADD CONSTRAINT "fk_images_room" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "fk_bookings_room" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "fk_bookings_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
    }

}
